name: titled_nav_bar
description: A titled simple bottom navigation bar with creamy animation on click.
version: 1.0.0

homepage: https://github.com/ArmanKT/titled_nav_bar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true